# Generated by Django 5.0.2 on 2024-02-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
